// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDP_1dgl-lXmU81ZcmJ8HWCL3z9E3FxY4',
    appId: '1:16660634737:android:72c98776e79ba69f2f0fd0',
    messagingSenderId: '16660634737',
    projectId: 'hasadak-e13f0',
    storageBucket: 'hasadak-e13f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-K-auFZ14UIUgVi1dKdmfb8sZyFvLEck',
    appId: '1:16660634737:ios:10549912500da8172f0fd0',
    messagingSenderId: '16660634737',
    projectId: 'hasadak-e13f0',
    storageBucket: 'hasadak-e13f0.firebasestorage.app',
    iosBundleId: 'com.example.hasadak',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPS-97WIL2v_EXWBHmZ9pRbggVE6JeSyw',
    appId: '1:1048737175320:web:c927cc4b8face596f6306d',
    messagingSenderId: '1048737175320',
    projectId: 'hasadak-f6297',
    authDomain: 'hasadak-f6297.firebaseapp.com',
    storageBucket: 'hasadak-f6297.firebasestorage.app',
    measurementId: 'G-7SN1B053VE',
  );

}